name: Skills
main: zinnia.skills.main.Skills
version: 1.0
author: Zinnia James
commands:
  Skills:
    description: General use of the skills plugin
    usage: /skills [Arguments, if any]
    aliases: [skill, skillmenu, skillsmenu]
permissions:
  skills.tier.one: # 1
    description: Gives the tier one permission, that may effect some player stats (Usually handled within plugin)
    default: false
  skills.tier.two: # 2
    description: Gives the tier two permission, that may effect some player stats (Usually handled within plugin)
    default: false
  skills.tier.three: # 3
    description: Gives the tier three permission, that may effect some player stats (Usually handled within plugin)
    default: false
  skills.tier.four: # 4
    description: Gives the tier four permission, that may effect some player stats (Usually handled within plugin)
    default: false
  skills.tier.five: # 5
    description: Gives the tier five permission, that may effect some player stats (Usually handled within plugin)
    default: false
  skills.tier.six: # 6
    description: Gives the tier six permission, that may effect some player stats (Usually handled within plugin)
    default: false
  skills.tier.seven: # 7
    description: Gives the tier seven permission, that may effect some player stats (Usually handled within plugin)
    default: false
  skills.tier.eight: # 8
    description: Gives the tier eight permission, that may effect some player stats (Usually handled within plugin)
    default: false
  skills.tier.nine: # 9
    description: Gives the tier nine permission, that may effect some player stats (Usually handled within plugin)
    default: false  
  skills.tier.Ten: # 10
    description: Gives the tier ten permission, that may effect some player stats (Usually handled within plugin)
    default: false
